# Generated by Django 5.0 on 2025-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('email', models.CharField(max_length=255, verbose_name='E-Mail')),
                ('age', models.IntegerField(blank=True, verbose_name='年齢')),
            ],
        ),
    ]
