# Generated by Django 5.0 on 2025-03-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_company', models.CharField(max_length=255, verbose_name='会社')),
                ('contact_person', models.CharField(max_length=255, verbose_name='担当者名')),
                ('property_address', models.CharField(max_length=255, verbose_name='物件住所')),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='見積もり')),
                ('layout_memo', models.TextField(blank=True, verbose_name='間取りメモ')),
                ('sunlight_memo', models.TextField(blank=True, verbose_name='日当たりメモ')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('created_by', models.CharField(max_length=255, verbose_name='作成者')),
                ('updated_by', models.CharField(max_length=255, verbose_name='更新者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
